# this is only for local development purposes
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kenora
      POSTGRES_PASSWORD: kenora
      POSTGRES_DB: kenora
    ports:
      - "5433:5432"
    volumes:
      - kenora_pg:/var/lib/postgresql/data
      - ./docker/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kenora -d kenora"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  kenora_pg:
